ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "rack" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "scheduling" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "prescriptionOnly" BOOLEAN NOT NULL DEFAULT false;
