import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Activity, ArrowDownLeft, ArrowUpRight, BarChart3, Boxes, CircleDollarSign,
  ClipboardList, CreditCard, Database, FileText, LayoutDashboard, LogOut,
  Menu, Package, PanelLeftClose, Plus, RotateCcw, Search, Settings2, ShieldCheck,
  ShoppingCart, Store, Truck, UserRound, Users, Wallet, X
} from 'lucide-react';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

const endpointGroups = [
  { label: 'Overview', icon: LayoutDashboard, items: [{ key: 'dashboard', label: 'Command center', path: '/dashboard' }] },
  { label: 'Catalog', icon: Package, items: [{ key: 'products', label: 'Products', path: '/products' }, { key: 'batches', label: 'Product batches', path: '/products/:productId/batches' }, { key: 'suppliers-products', label: 'Product suppliers', path: '/products/:productId/suppliers' }] },
  { label: 'Inventory', icon: Boxes, items: [{ key: 'stock', label: 'Stock control', path: '/products/:productId/stock' }, { key: 'movements', label: 'Stock movements', path: '/products/:productId/stock/movements' }] },
  { label: 'Commerce', icon: ShoppingCart, items: [{ key: 'purchases', label: 'Purchases', path: '/purchases' }, { key: 'sales', label: 'Sales register', path: '/sales' }, { key: 'returns', label: 'Returns', path: '/sales/:saleId/return' }, { key: 'payments', label: 'Payments', path: '/sales/:saleId/payments' }] },
  { label: 'Relationships', icon: Users, items: [{ key: 'suppliers', label: 'Suppliers', path: '/suppliers' }, { key: 'customers', label: 'Customers', path: '/customers' }, { key: 'ledgers', label: 'Customer & supplier ledgers', path: '/customers/:customerId/ledger' }] },
  { label: 'Administration', icon: ShieldCheck, items: [{ key: 'users', label: 'Team access', path: '/users' }, { key: 'api', label: 'API coverage', path: 'all' }] }
];

const records = {
  products: [{ name: 'Amoxicillin 500mg', sku: 'AMX-500-CAP', category: 'Antibiotic', stock: '248', status: 'In stock' }, { name: 'Metformin 850mg', sku: 'MET-850-TAB', category: 'Diabetes', stock: '92', status: 'Low stock' }, { name: 'Cetirizine 10mg', sku: 'CET-010-TAB', category: 'Allergy', stock: '620', status: 'In stock' }, { name: 'Atorvastatin 20mg', sku: 'ATO-020-TAB', category: 'Cardiology', stock: '0', status: 'Out of stock' }],
  suppliers: [{ name: 'Northstar Pharma Ltd.', contact: 'Amina Yusuf', balance: '$18,420', status: 'Active' }, { name: 'Medline Distribution', contact: 'David Chen', balance: '$6,850', status: 'Active' }, { name: 'CuraLife Wholesale', contact: 'Sofia Martins', balance: '$0', status: 'On hold' }],
  customers: [{ name: 'Cedar Grove Clinic', contact: 'clinic@cedargrove.com', balance: '$1,240', status: 'Credit account' }, { name: 'Westside Pharmacy', contact: 'orders@westside.co', balance: '$0', status: 'Clear' }, { name: 'Dr. Lena Okafor', contact: 'lena.okafor@clinic.com', balance: '$320', status: 'Credit account' }],
  sales: [{ id: 'SAL-1048', customer: 'Cedar Grove Clinic', date: '24 Aug 2026', total: '$2,840.00', status: 'Paid' }, { id: 'SAL-1047', customer: 'Westside Pharmacy', date: '24 Aug 2026', total: '$1,120.50', status: 'Pending' }, { id: 'SAL-1046', customer: 'Dr. Lena Okafor', date: '23 Aug 2026', total: '$486.00', status: 'Paid' }],
  purchases: [{ id: 'PUR-0231', supplier: 'Northstar Pharma Ltd.', date: '24 Aug 2026', total: '$8,420.00', status: 'Received' }, { id: 'PUR-0230', supplier: 'Medline Distribution', date: '22 Aug 2026', total: '$4,650.00', status: 'Part received' }, { id: 'PUR-0229', supplier: 'CuraLife Wholesale', date: '20 Aug 2026', total: '$2,190.00', status: 'Draft' }]
};

const apiRoutes = [
  ['Auth', 'POST /auth/register', 'Register a user'], ['Auth', 'POST /auth/login', 'Create a session'], ['Auth', 'GET /auth/me', 'Current user'], ['Auth', 'GET /auth/admin-test', 'Admin authorization'], ['Auth', 'GET /auth/role-test', 'Role authorization'],
  ['Dashboard', 'GET /dashboard', 'Operational KPIs'], ['Products', 'GET /products', 'List products'], ['Products', 'GET /products/:productId', 'Product detail'], ['Products', 'POST /products', 'Create product'],
  ['Product suppliers', 'GET /products/:productId/suppliers', 'List product suppliers'], ['Product suppliers', 'POST /products/:productId/suppliers', 'Add product supplier'], ['Product suppliers', 'PATCH /products/:productId/suppliers/:supplierId', 'Update product supplier'], ['Product suppliers', 'DELETE /products/:productId/suppliers/:supplierId', 'Remove product supplier'], ['Product suppliers', 'GET /suppliers/:supplierId/products', 'List supplier products'], ['Batches', 'GET /products/:productId/batches', 'List batches'], ['Batches', 'GET /batches/:batchId', 'Batch detail'], ['Batches', 'POST /products/:productId/batches', 'Create batch'], ['Batches', 'PATCH /batches/:batchId', 'Update batch'], ['Batches', 'DELETE /batches/:batchId', 'Delete batch'],
  ['Stock', 'GET /products/:productId/stock', 'Product stock'], ['Stock', 'GET /batches/:batchId/stock', 'Batch stock'], ['Stock', 'POST /batches/:batchId/stock', 'Add stock'], ['Stock', 'POST /batches/:batchId/stock/adjust', 'Adjust stock'], ['Stock', 'POST /batches/:batchId/stock/reserve', 'Reserve stock'], ['Stock', 'POST /batches/:batchId/stock/release', 'Release stock'], ['Stock', 'GET /products/:productId/stock/movements', 'Product movements'], ['Stock', 'GET /batches/:batchId/stock/movements', 'Batch movements'], ['Stock', 'POST /batches/:batchId/stock/sell', 'Sell stock'], ['Stock', 'POST /batches/:batchId/stock/sales-return', 'Sales return stock'], ['Stock', 'POST /batches/:batchId/stock/purchase-return', 'Purchase return stock'], ['Stock', 'POST /batches/:batchId/stock/damage', 'Damage stock'], ['Stock', 'POST /batches/:batchId/stock/confirm-sale', 'Confirm sale'], ['Stock', 'POST /batches/:batchId/stock/expire', 'Expire stock'], ['Stock', 'POST /batches/:batchId/stock/transfer', 'Transfer stock'],
  ['Purchases', 'POST /purchases', 'Create purchase'], ['Purchases', 'GET /purchases', 'List purchases'], ['Purchases', 'GET /purchases/:purchaseId', 'Purchase detail'], ['Purchases', 'POST /purchases/:purchaseId/return', 'Purchase return'], ['Payments', 'POST /purchases/:purchaseId/payments', 'Purchase payment'], ['Payments', 'GET /purchases/:purchaseId/payments', 'Purchase payments'],
  ['Sales', 'POST /sales', 'Create sale'], ['Sales', 'GET /sales', 'List sales'], ['Sales', 'GET /sales/:id', 'Sale detail'], ['Sales', 'POST /sales/:saleId/return', 'Sales return'], ['Payments', 'POST /sales/:saleId/payments', 'Sale payment'], ['Payments', 'GET /sales/:saleId/payments', 'Sale payments'],
  ['Suppliers', 'GET /suppliers', 'List suppliers'], ['Suppliers', 'GET /suppliers/:id', 'Supplier detail'], ['Suppliers', 'POST /suppliers', 'Create supplier'], ['Suppliers', 'PATCH /suppliers/:id', 'Update supplier'], ['Suppliers', 'GET /suppliers/:supplierId/ledger', 'Supplier ledger'], ['Customers', 'GET /customers', 'List customers'], ['Customers', 'GET /customers/:id', 'Customer detail'], ['Customers', 'POST /customers', 'Create customer'], ['Customers', 'PATCH /customers/:id', 'Update customer'], ['Customers', 'GET /customers/:customerId/ledger', 'Customer ledger'], ['Users', 'GET /users', 'List users'], ['Users', 'GET /users/:id', 'User detail'], ['Users', 'POST /users', 'Create user'], ['Users', 'PATCH /users/:id', 'Update user']
];

async function api(path, options = {}) {
  const token = localStorage.getItem('pharma_token');
  const response = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || `Request failed (${response.status})`);
  return data;
}

function App() {
  const [active, setActive] = useState('dashboard');
  const [query, setQuery] = useState('');
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('pharma_user') || 'null'));
  const [showLogin, setShowLogin] = useState(false);
  const [notice, setNotice] = useState('');

  useEffect(() => { if (user) api('/auth/me').catch(() => { localStorage.removeItem('pharma_token'); setUser(null); }); }, [user]);
  const activeItem = endpointGroups.flatMap(group => group.items).find(item => item.key === active) || endpointGroups[0].items[0];
  const filteredRoutes = useMemo(() => apiRoutes.filter(route => route.join(' ').toLowerCase().includes(query.toLowerCase())), [query]);

  const logout = () => { localStorage.removeItem('pharma_token'); localStorage.removeItem('pharma_user'); setUser(null); setNotice('Session ended'); };
  const createRecord = () => setNotice(`New ${activeItem.label.toLowerCase()} workspace ready for entry`);

  return <div className="app-shell">
    <aside className={`sidebar ${sidebarOpen ? '' : 'collapsed'}`}>
      <div className="brand"><div className="brand-mark"><Activity size={19} /></div><div className="brand-copy"><strong>verde</strong><span>pharmacy ERP</span></div>{sidebarOpen && <button className="icon-btn sidebar-toggle" onClick={() => setSidebarOpen(false)} aria-label="Collapse sidebar"><PanelLeftClose size={17} /></button>}</div>
      <div className="workspace"><div className="store-icon"><Store size={16} /></div><div><strong>Harbor Health</strong><span>Central branch</span></div><span className="live-dot" /></div>
      <nav>{endpointGroups.map(group => <div className="nav-group" key={group.label}><div className="nav-label">{sidebarOpen ? group.label : <group.icon size={15} />}</div>{group.items.map(item => <button className={`nav-item ${active === item.key ? 'selected' : ''}`} key={item.key} onClick={() => setActive(item.key)} title={item.label}>{<group.icon size={17} />}<span>{sidebarOpen && item.label}</span>{sidebarOpen && active === item.key && <span className="nav-active" />}</button>)}</div>)}</nav>
      <div className="sidebar-footer"><button className="nav-item"><Settings2 size={17} /><span>{sidebarOpen && 'Settings'}</span></button><button className="profile" onClick={user ? logout : () => setShowLogin(true)}><div className="avatar">{user ? (user.name || user.email || 'U').slice(0, 1).toUpperCase() : '?'}</div>{sidebarOpen && <span><strong>{user?.name || 'Guest operator'}</strong><small>{user?.role || 'Sign in to sync'}</small></span>}{sidebarOpen && (user ? <LogOut size={15} /> : <ArrowUpRight size={15} />)}</button></div>
    </aside>
    {!sidebarOpen && <button className="floating-menu" onClick={() => setSidebarOpen(true)} aria-label="Open sidebar"><Menu size={18} /></button>}
    <main className="main-content">
      <header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{activeItem.label}</strong></div><div className="top-actions"><div className="global-search"><Search size={16} /><input placeholder="Search workspace" value={query} onChange={event => setQuery(event.target.value)} /><kbd>Ctrl K</kbd></div><button className="icon-btn"><Activity size={18} /></button><div className="top-avatar">{user ? (user.name || 'U').slice(0, 1).toUpperCase() : 'G'}</div></div></header>
      <div className="page">
        <div className="page-heading"><div><p className="eyebrow">Tuesday, 25 August 2026 <span className="status-pill"><span className="live-dot" /> Systems operational</span></p><h1>{activeItem.key === 'dashboard' ? 'Good morning, operator.' : activeItem.label}</h1><p className="subtitle">{activeItem.key === 'dashboard' ? 'Here is the pulse of Harbor Health today.' : `Manage ${activeItem.label.toLowerCase()} across your pharmacy network.`}</p></div><button className="primary-btn" onClick={createRecord}><Plus size={17} /> New {activeItem.key === 'dashboard' ? 'transaction' : activeItem.label.replace('Product ', '')}</button></div>
        {notice && <div className="notice"><ShieldCheck size={16} /> {notice}<button onClick={() => setNotice('')}><X size={14} /></button></div>}
        {activeItem.key === 'dashboard' ? <Dashboard setActive={setActive} /> : activeItem.key === 'api' ? <ApiCoverage routes={filteredRoutes} /> : <DataView type={activeItem.key} query={query} />}
      </div>
    </main>
    {showLogin && <Login onClose={() => setShowLogin(false)} onLogin={(nextUser) => { setUser(nextUser); setShowLogin(false); }} />}
  </div>;
}

function Dashboard({ setActive }) { return <>
  <section className="kpi-grid"><Kpi icon={CircleDollarSign} label="Revenue this month" value="$84,260" change="+12.8%" tone="green" /><Kpi icon={ShoppingCart} label="Sales today" value="$4,446" change="+8.2%" tone="blue" /><Kpi icon={Boxes} label="Inventory value" value="$216,840" change="+4.6%" tone="amber" /><Kpi icon={Wallet} label="Outstanding balance" value="$26,830" change="-3.1%" tone="coral" /></section>
  <section className="dashboard-grid"><div className="panel revenue-panel"><div className="panel-heading"><div><span className="panel-kicker">Revenue overview</span><h2>$84,260.00 <span className="trend up">+12.8%</span></h2></div><select><option>Last 30 days</option><option>Last 90 days</option></select></div><div className="chart"><div className="chart-y"><span>$10k</span><span>$7.5k</span><span>$5k</span><span>$2.5k</span><span>$0</span></div><div className="chart-area"><div className="grid-lines" /> <svg viewBox="0 0 640 220" preserveAspectRatio="none" aria-label="Revenue trend"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#4a9884" stopOpacity=".30" /><stop offset="1" stopColor="#4a9884" stopOpacity="0" /></linearGradient></defs><path d="M0,172 C45,155 56,164 92,139 S155,160 190,111 S238,118 271,126 S318,74 355,102 S407,108 440,66 S490,91 525,54 S575,83 640,20 L640,220 L0,220Z" fill="url(#area)" /><path d="M0,172 C45,155 56,164 92,139 S155,160 190,111 S238,118 271,126 S318,74 355,102 S407,108 440,66 S490,91 525,54 S575,83 640,20" fill="none" stroke="#4a9884" strokeWidth="3" /></svg><div className="chart-months"><span>01 Aug</span><span>08 Aug</span><span>15 Aug</span><span>22 Aug</span><span>25 Aug</span></div></div></div></div><div className="panel inventory-panel"><div className="panel-heading"><div><span className="panel-kicker">Inventory health</span><h2>Stock at a glance</h2></div><button className="text-btn" onClick={() => setActive('stock')}>View control <ArrowUpRight size={14} /></button></div><div className="donut-wrap"><div className="donut"><div><strong>1,284</strong><span>SKUs tracked</span></div></div><div className="legend"><div><i className="dot green" />In stock <strong>78%</strong></div><div><i className="dot amber" />Low stock <strong>16%</strong></div><div><i className="dot coral" />Out of stock <strong>6%</strong></div></div></div></div></section>
  <section className="lower-grid"><div className="panel table-panel"><div className="panel-heading"><div><span className="panel-kicker">Needs attention</span><h2>Stock alerts</h2></div><button className="text-btn" onClick={() => setActive('products')}>See all <ArrowUpRight size={14} /></button></div><table><thead><tr><th>Product</th><th>SKU</th><th>Available</th><th>Status</th><th /></tr></thead><tbody>{records.products.slice(0, 3).map(item => <tr key={item.sku}><td><div className="product-cell"><div className="product-icon"><Package size={15} /></div><strong>{item.name}</strong></div></td><td className="muted">{item.sku}</td><td>{item.stock} units</td><td><Status value={item.status} /></td><td><button className="row-arrow"><ArrowUpRight size={15} /></button></td></tr>)}</tbody></table></div><div className="panel activity-panel"><div className="panel-heading"><div><span className="panel-kicker">Live feed</span><h2>Recent activity</h2></div><button className="icon-btn"><FileText size={16} /></button></div><ActivityItem icon={ShoppingCart} title="Sale SAL-1048 completed" detail="Cedar Grove Clinic · $2,840.00" time="8 min ago" tone="green" /><ActivityItem icon={Truck} title="Purchase PUR-0231 received" detail="Northstar Pharma Ltd. · 48 items" time="34 min ago" tone="blue" /><ActivityItem icon={ArrowDownLeft} title="Payment recorded" detail="Westside Pharmacy · $1,120.50" time="1 hr ago" tone="amber" /><ActivityItem icon={RotateCcw} title="Return requested" detail="Atorvastatin 20mg · 2 units" time="2 hrs ago" tone="coral" /></div></section>
</> }

function Kpi({ icon: Icon, label, value, change, tone }) { return <div className="kpi"><div className={`kpi-icon ${tone}`}><Icon size={19} /></div><div className="kpi-body"><span>{label}</span><strong>{value}</strong><small className={change[0] === '-' ? 'down' : ''}>{change} <em>vs last month</em></small></div><BarChart3 className="kpi-spark" size={42} /></div> }
function Status({ value }) { const tone = value.toLowerCase().includes('out') || value.toLowerCase().includes('hold') ? 'coral' : value.toLowerCase().includes('low') || value.toLowerCase().includes('pending') || value.toLowerCase().includes('draft') ? 'amber' : 'green'; return <span className={`status ${tone}`}><i />{value}</span> }
function ActivityItem({ icon: Icon, title, detail, time, tone }) { return <div className="activity-item"><div className={`activity-icon ${tone}`}><Icon size={16} /></div><div><strong>{title}</strong><span>{detail}</span></div><time>{time}</time></div> }

function DataView({ type, query }) { const key = type === 'customers' ? 'customers' : type === 'suppliers' ? 'suppliers' : type === 'sales' ? 'sales' : type === 'purchases' ? 'purchases' : 'products'; const rows = records[key].filter(row => Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase())); const columns = Object.keys(rows[0] || records[key][0]); return <section className="panel full-table"><div className="panel-toolbar"><div><span className="panel-kicker">Connected to {API_URL.replace('/api', '')}</span><h2>{rows.length} records <span className="record-count">Live workspace</span></h2></div><div className="toolbar-actions"><div className="table-search"><Search size={15} /><input placeholder={`Filter ${type}`} value={query} readOnly /></div><button className="secondary-btn"><FileText size={15} /> Export</button></div></div><table><thead><tr>{columns.map(column => <th key={column}>{column.replace(/([A-Z])/g, ' $1')}</th>)}<th /></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || row.sku || row.name}>{columns.map(column => <td key={column}>{column === 'status' ? <Status value={row[column]} /> : column === 'name' ? <div className="product-cell"><div className="product-icon"><Database size={15} /></div><strong>{row[column]}</strong></div> : <span className={column === 'contact' || column === 'sku' ? 'muted' : ''}>{row[column]}</span>}</td>)}<td><button className="row-arrow"><ArrowUpRight size={15} /></button></td></tr>)}</tbody></table></section> }
function ApiCoverage({ routes }) { return <section className="panel full-table"><div className="panel-toolbar"><div><span className="panel-kicker">Backend contract</span><h2>{routes.length} registered endpoints <span className="record-count">Authenticated API</span></h2></div><div className="api-base"><Activity size={15} /> {API_URL}</div></div><table><thead><tr><th>Domain</th><th>Method & path</th><th>Capability</th><th>Access</th></tr></thead><tbody>{routes.map(([domain, path, description]) => <tr key={path}><td><span className="domain-label">{domain}</span></td><td><code className={path.startsWith('GET') ? 'get' : path.startsWith('POST') ? 'post' : 'patch'}>{path}</code></td><td>{description}</td><td><Status value="Authenticated" /></td></tr>)}</tbody></table></section> }
function Login({ onClose, onLogin }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); setError(''); try { const data = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); const nextUser = data.user || data.data?.user || { email }; localStorage.setItem('pharma_token', data.token || data.data?.token || ''); localStorage.setItem('pharma_user', JSON.stringify(nextUser)); onLogin(nextUser); } catch (err) { setError(err.message); } }; return <div className="modal-backdrop"><div className="login-modal"><button className="modal-close" onClick={onClose}><X size={17} /></button><div className="brand login-brand"><div className="brand-mark"><Activity size={19} /></div><div className="brand-copy"><strong>verde</strong><span>pharmacy ERP</span></div></div><p className="eyebrow">Secure workspace access</p><h2>Welcome back.</h2><p className="subtitle">Sign in to sync your operations with the live API.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required placeholder="you@harborhealth.com" /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} required placeholder="********" /></label>{error && <div className="form-error">{error}</div>}<button className="primary-btn login-submit">Sign in <ArrowUpRight size={16} /></button></form></div></div> }

createRoot(document.getElementById('root')).render(<App />);

export default App;